const fs = require('fs');
const path = require('path');

// Read .env file from parent directory (for local dev) or current directory
// Try parent first (standard repo structure), then current (if deployed in flat structure)
let envPath = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
    envPath = path.join(__dirname, '.env');
}

let envVars = {};

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
        line = line.trim();
        // Skip comments and empty lines
        if (line.startsWith('#') || !line) return;

        const [key, ...valueParts] = line.split('=');
        if (key && valueParts.length > 0) {
            const value = valueParts.join('=').trim();
            // Remove quotes if present
            envVars[key.trim()] = value.replace(/^["'](.*)["']$/, '$1');
        }
    });
}

// Helper to get env var (System > .env > Default)
const getEnv = (key, defaultValue = '') => {
    return process.env[key] || envVars[key] || defaultValue;
};

// Generate config.js content
const configContent = `// ============================================
// SUPABASE CONFIGURATION - AUTO-GENERATED
// ============================================
// This file is auto-generated from .env by generate-config.js
// DO NOT edit this file manually - your changes will be overwritten
// DO NOT commit this file to version control

// Supabase credentials
window.SUPABASE_URL = '${getEnv('SUPABASE_URL')}';
window.SUPABASE_ANON_KEY = '${getEnv('SUPABASE_ANON_KEY')}';

// Backend API base URL
window.API_BASE_URL = '${getEnv('API_BASE_URL', 'http://localhost:8000')}/api';

// Export config object for backward compatibility
window.APP_CONFIG = {
    supabase: {
        url: window.SUPABASE_URL,
        anonKey: window.SUPABASE_ANON_KEY
    },
    apiBaseUrl: window.API_BASE_URL
};
`;

// Write to config.js in the current directory (frontend)
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Config generated successfully');
console.log('📁 Written to: config.js');
console.log('');
console.log('⚠️  IMPORTANT: Add config.js to .gitignore to prevent committing secrets');
